tintas = {
            'Selecione um modelo': {'rendimento': 0.1, 'diluicao':''},
            'Pinta Piso 3,6L': {'rendimento': 14, 'diluicao':'Superfícies não pintadas: diluir até 30% com água potável. Superfícies pintadas e demais superfícies: diluir até 20%'},
            'Pinta Piso 18L': {'rendimento': 70, 'diluicao':'Superfícies não pintadas: diluir até 30% com água potável. Superfícies pintadas e demais superfícies: diluir até 20%'},
            'Super Lavável 800ml':{'rendimento':4.9,'diluicao':'Diluir até 20% com água potável.'},
            'Super Lavável 900ml':{'rendimento':5.5,'diluicao':'Diluir até 20% com água potável.'},
            'Super Lavável 3,2L':{'rendimento':19,'diluicao':'Diluir até 20% com água potável.'},
            'Super Lavável 3,6L':{'rendimento':22,'diluicao':'Diluir até 20% com água potável.'},
            'Super Lavável 16L':{'rendimento':98,'diluicao':'Diluir até 20% com água potável.'},
            'Super Lavável 18L':{'rendimento':110,'diluicao':'Diluir até 20% com água potável.'},
            '3 EM 1 3,2L':{'rendimento':22,'diluicao':'Diluir até 40% com água potável.'},
            '3 EM 1 3,6L':{'rendimento':25,'diluicao':'Diluir até 40% com água potável.'},
            '3 EM 1 16L':{'rendimento':110,'diluicao':'Diluir até 40% com água potável.'},
            '3 EM 1 18L':{'rendimento':125,'diluicao':'Diluir até 40% com água potável.'},
            'Bem Estar 3,6L':{'rendimento':44,'diluicao':'Pronto para uso.'},
            'Decora Matte 800ml':{'rendimento':6.6,'diluicao':'Diluir até 20% com água potável'},
            'Decora Matte 900ml':{'rendimento':7.5,'diluicao':'Diluir até 20% com água potável'},
            'Decora Matte 3,2L':{'rendimento':26,'diluicao':'Diluir até 20% com água potável'},
            'Decora Matte 3,6L':{'rendimento':30,'diluicao':'Diluir até 20% com água potável'},
            'Decora Matte 16L':{'rendimento':133,'diluicao':'Diluir até 20% com água potável'},
            'Decora Matte 18L':{'rendimento':150,'diluicao':'Diluir até 20% com água potável'},
            'Decora Seda 800ml':{'rendimento':4.6,'diluicao':'Diluir até 20% com água potável'},
            'Decora Seda 900ml':{'rendimento':5.2,'diluicao':'Diluir até 20% com água potável'},
            'Decora Seda 3,2L':{'rendimento':18,'diluicao':'Diluir até 20% com água potável'},
            'Decora Seda 3,6L':{'rendimento':21,'diluicao':'Diluir até 20% com água potável'},
            'Decora Seda 16L':{'rendimento':93,'diluicao':'Diluir até 20% com água potável'},
            'Decora Seda 18L':{'rendimento':105,'diluicao':'Diluir até 20% com água potável'},
            'Decora Diamante 800ml':{'rendimento':4.9,'diluicao':'Diluir até 20% com água potável'},
            'Decora Diamante 900ml':{'rendimento':5.5,'diluicao':'Diluir até 20% com água potável'},
            'Decora Diamante 3,2L':{'rendimento':19,'diluicao':'Diluir até 20% com água potável'},
            'Decora Diamante 3,6L':{'rendimento':22,'diluicao':'Diluir até 20% com água potável'},
            'Decora Diamante 16L':{'rendimento':98,'diluicao':'Diluir até 20% com água potável'},
            'Decora Diamante 18L':{'rendimento':110,'diluicao':'Diluir até 20% com água potável'},
            'Renova 800ml':{'rendimento':5.5,'diluicao':'1ª demão: diluir até 40% com água potável. Demais demãos: diluir até 20% com água potável.'},
            'Renova 3,2L':{'rendimento':22,'diluicao':'1ª demão: diluir até 40% com água potável. Demais demãos: diluir até 20% com água potável.'},
            'Renova 16L':{'rendimento':110,'diluicao':'1ª demão: diluir até 40% com água potável. Demais demãos: diluir até 20% com água potável.'},
            'Renova 18L':{'rendimento':125,'diluicao':'1ª demão: diluir até 40% com água potável. Demais demãos: diluir até 20% com água potável.'},
            'Renova Tetos 900ml':{'rendimento':4.5,'diluicao':'Pronto para uso.'},
            'Renova Tetos 3,6L':{'rendimento':18,'diluicao':'Pronto para uso.'},
            'Rende Muito 800ml':{'rendimento':4.7,'diluicao':'Diluir de 50% a 80% com água potável'},
            'Rende Muito 3,2L':{'rendimento':30,'diluicao':'Diluir de 50% a 80% com água potável'},
            'Rende Muito 16L':{'rendimento':150,'diluicao':'Diluir de 50% a 80% com água potável'},
            'Coralar Interior 3,6L':{'rendimento':18,'diluicao':'Diluir de 10% a 20% com água potável'},
            'Coralar Interior 15L':{'rendimento':75,'diluicao':'Diluir de 10% a 20% com água potável'},
            'Coralar Interior 18L':{'rendimento':90,'diluicao':'Diluir de 10% a 20% com água potável'},
            'Coralar Exterior e Interior 3,2L':{'rendimento':15,'diluicao':'Diluir até 20% com água potável'},
            'Coralar Exterior e Interior 3,6L':{'rendimento':20,'diluicao':'Diluir até 20% com água potável'},
            'Coralar Exterior e Interior 15L':{'rendimento':60,'diluicao':'Diluir até 20% com água potável'},
            'Coralar Exterior e Interior 16L':{'rendimento':75,'diluicao':'Diluir até 20% com água potável'},
            'Coralar Exterior e Interior 18L':{'rendimento':100,'diluicao':'Diluir até 20% com água potável'},
            'Hammerite 800ml':{'rendimento':100,'diluicao':'Pincel: pronto para uso | Trincha ou rolo: diluir de 5% a 10% com Aguarrás Coral | Pistola: diluir de 15% a 20%.'},
            'Hammerite 2,4L':{'rendimento':100,'diluicao':'Pincel: pronto para uso | Trincha ou rolo: diluir de 5% a 10% com Aguarrás Coral | Pistola: diluir de 15% a 20%.'},
            'Coralit 900ml':{'rendimento':19,'diluicao':'Diluir com Aguarrás Coral | Pincel, Trincha ou rolo: Diluir até 10% com Aguarrás Coral | Pistola: diluir até 20%.'},
            'Coralit 3,6L':{'rendimento':75,'diluicao':'Diluir com Aguarrás Coral | Pincel, Trincha ou rolo: Diluir até 10% com Aguarrás Coral | Pistola: diluir até 20%.'},
            'Tinta Grafite 900ml':{'rendimento':19,'diluicao':'Diluir com Aguarrás Coral | Pincel, Trincha ou rolo: Diluir até 10% com Aguarrás Coral | Pistola: diluir até 30%.'},
            'Tinta Grafite 3,6L':{'rendimento':75,'diluicao':'Diluir com Aguarrás Coral | Pincel, Trincha ou rolo: Diluir até 10% com Aguarrás Coral | Pistola: diluir até 30%.'},
            }

print(tintas['Selecione um modelo']['diluicao'])